{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-skellam
  version: {{ version|replace("-", "_") }}

source:
  fn: skellam_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/skellam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/skellam/skellam_{{ version }}.tar.gz
  sha256: fd016494436ff6e877909e390440e595a5dc2def8ab42eb79883f5038b5ebc64

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('skellam')"           # [not win]
    - "\"%R%\" -e \"library('skellam')\""  # [win]

about:
  home: http://r-forge.r-project.org/projects/healthqueues/
  license: GPL (>= 2)
  summary: 'Functions for the Skellam distribution, including: density (pmf), cdf, quantiles
    and regression.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
