travis:
  secure:
    BINSTAR_TOKEN: VJoAwTdWhDtatJ3WxFXiSUrxIx4C7N9hx0W8ABsaz/zooJ3uRBGwzwFONuCapUwQEI1bGRfuvQRQU9TM/Qoi796kzSx5/Ag0kLdScgZiR53y+PSSoAxOnzxSMllxJwr9mv7dUZbgcDdUB5KWLDzR4hKAADPUm1dt0NRBSU1SpcbK/uonrSD1mNVQxZZ7vVmN8nn3SHHNsz0lyeoLF2xn1d9aGH0PMtrVb3mNCQSh8WEQMrgT71Kp2bLRroQ6LC8rv5GsDi0k3jhjq3OZmojYgijOL/jsumaux6uwrAdaAGmgkweKD0xKdGj0c7k63bBiD7zkmSyTh/v3LT0LNVGzpSTx6zWPAf634IciS+CDVc+L0dNOKtrQcel1hsAFNobfVYmx5DPvdcAXb3J6e1YEGaa5vMBwMsOytMAmsWr6hNLOU72aaDrHN8WIVDiwzajRKKMRRzaTXRVoql9XaRo2XE5ksrJzuOZI/wg7Sv+WoskBNDr/CO2lAjd+HYhUduV5vsWdKRkvxj0kC1K58D5vvY8dZvoSgOoSXW4wKautahUrq5W3M5GEjKaySwa9zICbKRnztUDuDtuv7s8+JO06hFCU+UFLzIcLvfMC2LkJjLzhxlmKu9M01VdpeoyMKnC7Ns4VvTjkSwNhBzDkK2UxyJIcolLVgdMnVKvEkqig/wY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
