travis:
  secure:
    BINSTAR_TOKEN: Gs0TMQTGpVlfVW6P//B79SIeBdnfaf/DXoIb9q0aIGCfsci302dNbXIxOC0ikLI7zoNN7bk0kMAgZVsv7JUvxHTvIkUYXbl05QIh582B3tfjkAWulIkveCGcul5JzAsCzghQneAz4zty2cw2ocJ4YtD97hCNIztLFeAWvnd5bu+l1jWMcpzrygqeWWt4ht18w81sXkC3RG9qVVwLey7yQarnG+8tyVtuITz4f+dHRKybA9acaFHxl0AR7ovh5RJy87b9c15PA1JsMAgdh3yWoNOJ31XYF8i81xYvS+9uJSs7rZJFvX89hh9Oq/8AClAGT0XpYzitCoSHKnaAaJjl3XLItWpQrrnh8CXoTh88odlhXIpqTa7E/QcW0KI0HYovXvPG495ft4KYAf4rNKhPIh2zFs30Sc0scfUXr60HLy/mTviWnDX43n0oW03PN50ejdhyHq0MdEZmDdXhA83F+ckR1witQb86PtPXda4YQ1D15rMDJCpwVAQ9TVx6HuHmK/BqTJ7DC9/9voUJZ3lQhqZr4FGV6iDetgsXGcIcBiRlnpq/RQuycSVQPOu3/3lqt8f7o7i34kjkpaGBRhEMApWrrYV6iyY7cNDzXPV9d+Kz+Yso1tntw4K2n3Mou1qln0xuxJ4UuoALD7ojLhjLrIPZ1pGPUs6RZCTlT6OeJzw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
