travis:
  secure:
    BINSTAR_TOKEN: dBgCUNueL6vWaiqTKiB6EYyLMSujBlzLK0iLFqLSh/wonXqdWGCKHDJ3t+afvziZgWhl3+JfFuZAuAxJYZub8C1U8/y65R+2H0AAM4QAk2vULMWeUzJfn6rzFljDzLQBcxPQbNNzFvoa24VlHjysPeMy06lUTMwd4Ox/Tko97aumwzvEnKKEHisDY/tQuBHmtytEalOg9q0In3LrqlqP4xNoydWjJjNYL+ekptjClMmUdWs7uAIK8po6BbfIty3ZS9e0Z+1nQ+6a5X2f5lNhc2CXWJImDt0xadCmqOftKUnUrFTAHdbyTTScVLudZAfjggEoSuNClDi9p8546Cb7d8glx6BRnmhAWu/quJ/a40FHzLAVVcfJ1KCt7BMYBmf93YbCLcK2uI0BmaD15uGiLpf30GW18obnhm3cX4TogipI3Msb7TbNoVkCrLVsciaYLOFPy3B/TEDss3U4EKbtMZOfiypeCntWzAX2iKNE5KmtwWgpljf8bJmvjq6kvPOCHioGvPGzOmFfzsM/1Zavq8t/wN5YDJrRjcMbh4+8vZtuqtkVqpmKYt3ynjsY1BgmQmhtqF6wwzM1vVUupT7pfrtXHbNgg4PTjW7MJM2hrbvv6aqCVzx/63scrDOUG/qQ/KafPxDivZlEopwMi42Z035IOT7XX053o1lYruhJKnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
