travis:
  secure:
    BINSTAR_TOKEN: iNkkFv9oM3J6Iq0U1hLTbgOsDa/wBvxU7s19Ys03FwGtWZj9pEgpOzc7zEcIxNxYrFulToLdArODIxbAcxPb5579NYo6dOvGgz6IoauRvXZrIhiGzPibxFJm2+Quo1e31KXBLXhxxXvnlShoM4dUj9jMN2JJkYwUBU4Une6KyyAuaCaQB2motcxiZ6P9ocB8NexANdkYy03z9vk0pQiwq9tpLP4Ik3MTUslQsRRXvE+5OuSqgRzW7bp9pc1fTOyJU5anosoTSwAaqYvEa/51+8o8lpacUfUQQKyof/MHfiGA2VSXPEYivg3aJCbjPtGla9KYVR8nMnOdnFxlTFpHkusmAnpuZOXulk1XD9LGh2spOmC+bM0RSgFRvo4C2PgBbo/aQOLvQLNysDtaTbwZk8IzV80t3yV8yKbXA80/owQ4qXJgdZlJGln7rleBVM+sVtEy9Zu14bqI0D7TNJWN3IMTPNfk/ueXqZHWluYva93OYjlkJxW3ZMRpsVYsrklu5p6cyaj4E3E/ZmpxaY01+v/W8SmO+27XUPmijXEsPObGg5LNzu859jWHFoOqOFbzmASOSy1mAS2ScXqXN6GUJOcf+AAnhvCumL9jiSgF8F9duFnsS1ycpH4eH1Owk8ayw4jIvnovJ95UQwrA58o/IbBUAcGW6zhzfSI7LFNjLzE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
